### ISSUE TITLE
incompatible with numpy 1.24.1

### ISSUE THREAD

**Issue by mperez-cdf** [norok2/raster_geometry#3]
It seems that raster-geometry uses numpy.float, which does not exist anymore on numpy 1.24 

I guess it's possible to replace it with numpy.single ( https://numpy.org/doc/stable/user/basics.types.html )

**Comment by norok2** [comment]
Actually, it's a typo. It should have been `float_` which is an alias to `double`. I'll try to fix this ASAP

**Comment by AdnanAvdagic** [comment]
Any progress on this?

**Comment by norok2** [comment]
This was released to PyPI a couple of days ago. Can you confirm that it works for you?

**Comment by mperez-cdf** [comment]
> This was released to PyPI a couple of days ago. Can you confirm that it works for you?

Yes, it works !
